{
    'name': 'Ticket Pro - MFH',
    'version' : '1.2',
    'summary': 'Invoices & Payments',
    'sequence': 10,
    'description': """
Ticket Pro (TOTP)
================================
Allows users to configure
    """,
    'category': 'Accounting/Accounting',
    'website': 'https://www.marlonfalcon.com',
    'depends': ['base','mail'],
    'category': 'Extra Tools',
    'auto_install': False,
    'data': [
        'data/ir_config_parameter.xml',
        'security/groups.xml',
        'reports/report_tickets_details.xml',
        'reports/report_ticket_notes.xml',
        'views/ticket_pro_view.xml',
        'views/change_project_view.xml',
        'views/ticket_category_view.xml',
        'views/res_users.xml',
        'views/ticket_log_view.xml',
        'views/menu.xml',
        'views/ticket_control_view.xml',
        'views/progress_control_view.xml',
        'views/user_task_view.xml',
        'views/ticket_note_view.xml',
        'views/ticket_project_view.xml',
        'views/ticket_server.xml',
        'views/tproject_state_view.xml',
        'views/ticket_sprint_view.xml',
        'views/frequent_question_view.xml',
        'views/ticket_link_view.xml',
        'views/module_description_views.xml',
        'data/ir_sequence.xml',
        'data/ir_cron.xml',
        'data/ticket_pro_data.xml',
        'security/ir.model.access.csv',
        'wizards/report_tickets_pro_wzd.xml',
        'views/directory_partner_views.xml',
        'views/meeting_attendance_views.xml',
        'views/class_ticket_views.xml',

    ],
    'license': 'LGPL-3',
}